[bar.widgets]
background_opacity = 0.1099999975413084
capsule_border = "on_surface"
capsule_fill = "surface"
capsule_opacity = 0.35999999195337296
capsule_padding = 9.0
capsule_radius = 10
center = [ "date", "media" ]
contact_shadow = true
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_edge = 4
padding = 4
scale = 0.80000000447034836
start = [ "workspaces", "group:g1" ]
thickness = 28

    [[bar.widgets.capsule_group]]
    border = "tertiary"
    enabled = true
    fill = "secondary"
    foreground = "primary"
    id = "g1"
    members = [ "cpu", "temp", "ram", "network_rx" ]
    opacity = 0.05000000074505806
    padding = 9.0
    radius = 10.0

[battery]
warning_threshold = 20

[calendar]
enabled = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 1.0
cross_axis_padding = 2
enabled = true
icon_size = 30
item_spacing = 0
launcher_position = "start"
main_axis_padding = 8
pinned = [ "google-chrome", "pcmanfm-qt" ]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.84999998100101948

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1720.0
    cy = 1321.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 267.0
    cy = 734.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[notification]
background_opacity = 1.0

[osd]
background_opacity = 1.0

[plugins]
enabled = []

[shell]
app_icon_colorize = true
font_family = "FiraCode Nerd Font"
niri_overview_type_to_launch_enabled = true

    [shell.launcher.providers.emoji]
    global = true

    [shell.panel]
    clipboard_position = "auto"
    list_item_background = true
    open_near_click_session = true
    polkit_position = "auto"
    session_placement = "floating"
    wallpaper_placement = "floating"

    [shell.shadow]
    alpha = 0.48999998904764652

[theme]
custom_palette = "stylix"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [
        "pear-desktop",
        "zen-browser",
        "neovim",
        "heroiclauncher",
        "prismlauncher",
        "steam",
        "zathura",
        "bat",
        "lazygit",
        "yazi"
    ]

        [theme.templates.user.fish]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/colors-template.fish"
        output_path = "$XDG_CONFIG_HOME/fish/generated-colors.fish"
        post_hook = "fish $XDG_CONFIG_HOME/fish/generated-colors.fish"

        [theme.templates.user.tmux]
        input_path = "$XDG_CONFIG_HOME/noctalia/templates/tmux.conf"
        output_path = "$XDG_CONFIG_HOME/tmux/noctalia.conf"
        post_hook = "tmux source-file $XDG_CONFIG_HOME/tmux/noctalia.conf 2>/dev/null || true"

[wallpaper.automation]
interval_seconds = 300

[wallpaper.default]
path = "/home/Jester/Pictures/Wallpapers/ShadowsOf.jpg"

[wallpaper.last]
path = "/home/Jester/Pictures/Wallpapers/ShadowsOf.jpg"

[wallpaper.monitors.DP-1]
path = "/home/Jester/Pictures/Wallpapers/ShadowsOf.jpg"

[weather]
unit = "imperial"

[widget.clock]
capsule = true
capsule_border = "primary"
capsule_padding = 11

[widget.date]
anchor = true
capsule = true
capsule_border = "outline"
capsule_padding = 13
format = "{:%H:%M %a %d %b}"

[widget.media]
capsule_padding = 9

[widget.network]
capsule = false
show_label = false

[widget.network_rx]
stat = "disk_pct"

[widget.sysmon]
custom_image_colorize = true
stat = "swap_pct"

[widget.workspaces]
capsule_opacity = 0.0
capsule_padding = 8
focused_output_only = true
labels_only_when_occupied = true
