[bar.widgets]
center = [ "workspaces" ]
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_edge = 4
padding = 4
scale = 0.80000000447034836
start = [ "clock", "date", "media" ]
thickness = 28

[battery]
warning_threshold = 20

[calendar]
enabled = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
background_opacity = 1.0
cross_axis_padding = 2
enabled = true
icon_size = 30
item_spacing = 0
launcher_position = "start"
main_axis_padding = 8
pinned = [ "google-chrome", "org.kde.dolphin" ]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.84999998100101948

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1720.0
    cy = 1321.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 267.0
    cy = 734.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[notification]
background_opacity = 1.0

[osd]
background_opacity = 1.0

[plugins]
enabled = [ "avivbintangaringga/nix-monitor" ]

[shell]
app_icon_colorize = true
font_family = "FiraCode Nerd Font"
niri_overview_type_to_launch_enabled = true

    [shell.panel]
    wallpaper_placement = "floating"

    [shell.shadow]
    alpha = 0.48999998904764652

[theme]
custom_palette = "stylix"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "ghostty", "kcolorscheme", "mango", "niri", "qt" ]
    community_ids = [ "zen-browser", "neovim", "steam", "bat", "lazygit", "yazi" ]

[wallpaper.automation]
interval_seconds = 300

[wallpaper.default]
path = "/home/Jester/Pictures/Wallpapers/Portal.jpg"

[wallpaper.last]
path = "/home/Jester/Pictures/Wallpapers/Portal.jpg"

[wallpaper.monitors.DP-1]
path = "/home/Jester/Pictures/Wallpapers/Portal.jpg"

[widget.clock]
capsule = true
capsule_border = "primary"
capsule_padding = 11

[widget.date]
capsule = true
capsule_border = "outline"
capsule_padding = 13

[widget.network]
capsule = true

[widget.sysmon]
custom_image_colorize = true
